Add missing header include required by __atoe
Whilst compiling with Open XL on z/OS, what usually would
appears as a warning surfaces as an error:
error: call to undeclared function '__atoe'; ISO C99 and later do
not support implicit function declarations
[-Wimplicit-function-declaration]

This change includes the header that declares this function.

Signed-off-by: Gaurav Chaudhari <Gaurav.Chaudhari@ibm.com>