Exclude tests for JDK12+
Excluding following tests:
TestRefreshGCSpecialClassesCache_BCI_EXTENDED_HCR -
UnsupportedOperationException: This feature requires ASM7
TestGCClassWithStaticRetransformInGencon -
UnsupportedOperationException: This feature requires ASM5


Signed-off-by: Jason Feng <fengj@ca.ibm.com>