Throw NoClassDefFoundError instead of TypeNotPresentException
When the VM is resolving a MethodType, NoClassDefFoundError should be
thrown instead of TypeNotPresentException.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>