Update test: IndyTest.test_indyn_ldc_invalid_type
Renamed test_indyn_ldc_invalid_type to
test_indyn_ldc_non_existent_class_methodtype.

Updated test to check for NoClassDefFoundError instead of
TypeNotPresentException.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>