Exclude tests for JDK12+
Excluding following tests:
TestFlushReflectionCache - NoSuchFieldException: annotations;
cmdLineTester_jvmtitests_hcr_ - NoSuchFieldException: methodAccessor;
TestRefreshGCSpecialClassesCache_BCI_FAST_HCR -
UnsupportedOperationException: This feature requires ASM7;
TestGCClassWithStaticRetransformInBalanced -
UnsupportedOperationException: This feature requires ASM5.



Signed-off-by: Jason Feng <fengj@ca.ibm.com>