ClassScanner should ignore "PermittedSubclasses" attribute in Java 17
Otherwise the inherited method (inappropriately) throws
  UnsupportedOperationException: This feature requires ASM9_EXPERIMENTAL

Signed-off-by: Keith W. Campbell <keithc@ca.ibm.com>