CRIU: correct type of pool elements in instanceObjects
The 'clazz' field of a J9Object isn't generally wide enough to properly
capture an object pointer: use j9object_t instead. This issue was
highlighted by a couple of cast errors in builds configured using
"--with-mixedrefs=no":

CRIUHelpers.cpp:195:52: error: cast to pointer from integer of different
size [-Werror=int-to-pointer-cast]
CRIUHelpers.cpp:334:44: error: cast from 'j9object_t {aka J9Object*}' to
'j9objectclass_t {aka unsigned int}' loses precision [-fpermissive]

Also add missing include directory required in UMA builds.

Signed-off-by: Keith W. Campbell <keithc@ca.ibm.com>