Throw correct exception when initialization already failed
When initialization has already failed for a class before, throw
`NoClassDefFoundError` with `ExceptionInInitializerError` as its cause
instead of the `Throwable` that caused the first initialization failure.

Fixes: #14080
Signed-off-by: Eric Yang <eric.yang@ibm.com>