Enable COMPUTED_GOTO on zLinux
USE_COMPUTED_GOTO is enabled on zLinux when compiling with gcc-7+. When
OpenJ9 is built using gcc-7 on zLinux, USE_COMPUTED_GOTO improves
startup performance by ~10% for DayTrader.

When compiling with USE_COMPUTED_GOTO enabled and gcc version > 4.6,
VMINLINE shouldn't be used with VM_BytecodeInterpreter::run. Otherwise,
the following compile error is encountered:

BytecodeInterpreter.hpp:8136:2: error: function ‘UDATA
VM_BytecodeInterpreter::run(J9VMThread*)’ can never be copied because it
saves address of local label in a static variable

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>