Remove unused var to fix compilation error on Windows
vmargs.c(342): error C2220: the following warning is treated as an error
vmargs.c(342): warning C4101: 'oldValue': unreferenced local variable

Related to https://github.com/eclipse-openj9/openj9/pull/22481

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>
(cherry picked from commit ea687a777097beabb779be53a91f32ebe8ca999f)