Remove unused privatePortLibrary
While compiling OpenJ9 with Clang 9.1.0 on OSX, the following error is
seen:

../unix/syshelp.c:257:2: error: unused variable 'privatePortLibrary'
[-Werror,-Wunused-variable]
        PORT_ACCESS_FROM_ENV(env);
        ^
../../oti/j9.h:242:53: note: expanded from macro 'PORT_ACCESS_FROM_ENV'
#define PORT_ACCESS_FROM_ENV(jniEnv) J9PortLibrary *privatePortLibrary =
(J9VMTHREAD_FROM_JNIENV(jniEnv))->javaVM->portLibrary
                                                    ^

syshelp.c::getPlatformFileEncoding requires port access only on LINUX.
The above error is fixed by enabling the call to PORT_ACCESS_FROM_ENV
only on LINUX.
                                                                                  
Also, fixed variable initialization and code formatting.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>