Fix test for free tag
Instead of the test succeeding, it would throw:
InvalidDataTypeException: U64 contains value larger than Long.MAX_VALUE

Signed-off-by: Keith W. Campbell <keithc@ca.ibm.com>