Update test_indyn_invalid_bootstrap_method and add API for Java version
JVM behavior has changed between Java 8 and Java 9. In Java 8,
BootstrapMethodError is thrown for non-existent bootstrap
method is used. In Java 9, NoSuchMethodError is thrown for non-existent
bootstrap method is used. Test,
IndyTest.test_indyn_invalid_bootstrap_method, has been updated to
account for change in JVM behavior.

Added an API for Java version: JavaVersion.isJava8(),
JavaVersion.isJava9() and JavaVersion.getJavaVersion(). Updated tests to
utilize the new API.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>