Fix undefined declarations of currentThread
Experienced `error: use of undeclared identifier '_currentThread'`
while building with in progress mixed references mode.

`_currentThread` is not accessible in VMHelpers, so it must be
passed into the function. Some references to `_currentThread`
should be `currentThread` instead.

Signed-off-by: Sharon Wang <sharon-wang-cpsc@outlook.com>