Add missing default switch case statement
While compiling OpenJ9 with Clang 9.1.0 on OSX, the following error is
seen:

com/ibm/jvmti/tests/followReferences/fr003.c:219:10: error: enumeration
value 'jvmtiPrimitiveTypeEnsureWideEnum' not handled in switch
[-Werror,-Wswitch]
        switch (primitiveType) {
                ^
com/ibm/jvmti/tests/followReferences/fr003.c:219:10: note: add missing
switch cases
        switch (primitiveType) {
                ^

The above error is resolved by adding the default switch case statement.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>