Handle optional fields in obsolete type
If a type is no longer present, create a fictitious StructureDescriptor
for its optional fields.

Code generated by PointerGenerator must anticipate NoClassDefFoundError.

Also
* don't return null from StructureDescriptor.getSuperName()
* remove unused field StructureDescriptor.pointerName
* update help messages

Signed-off-by: Keith W. Campbell <keithc@ca.ibm.com>