Real-time clock is not supported on OSX
In MetronomeAlarm.hpp, private field 'RTCfd' is used to store real-time
clock related information.

On OSX, real-time clock is not supported. So, private field 'RTCfd' is
unused. While compiling OpenJ9 with Clang 9.1.0 on OSX, the following
error is seen:

./MetronomeAlarm.hpp:103:8: error: private field 'RTCfd' is not used
[-Werror,-Wunused-private-field]

The declaration of private field 'RTCfd' is surrounded by '#if
defined(LINUX) && !defined(J9ZTPF)'. This resolves the compiler error on
OSX.

Also, fixed ifdefs related to RTCfd in MM_RTCAlarm::sleep().

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>