private field '_tokenCount' unused in BarrierSynchronization
While compiling OpenJ9 with Clang 9.1.0 on OSX, the following error is
seen:

./BarrierSynchronization.hpp:48:7: error: private field '_tokenCount' is
not used [-Werror,-Wunused-private-field]

private field _tokenCount is removed since it is unused.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>