Fix NoSuchFieldError in SCC DDR command
Catch NoSuchFieldError and NoSuchMethodError when running on an old core
where SH_CacheMap does not have field _ccTail. Fall back to code before
#6883 i.e. use cacheMap._cc() to set compositeCacheImpl in this case.

Fixes #12357

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>