Translate TypeNotPresentException to NoClassDefFoundError
While resolving bootstrap method handles, TypeNotPresentException is
currently thrown if a class is not found since we rely upon the
MethodType API.  But, NoClassDefFoundError should be thrown if a class
is not found while resolving bootstrap method handles. This change
translates TypeNotPresentException to NoClassDefFoundError while
resolving bootstrap method handles.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>