Fix 'char *' to 'unsigned char *' conversion errors
While compiling OpenJ9 with Clang 9.1.0 on OSX, the following compile
error is seen:

com/ibm/jvmti/tests/eventMethodEntryGrow/emeng001.c:99:38: error:
passing 'char *' to parameter of type 'unsigned char *' converts between
pointers to integer types with different sign [-Werror,-Wpointer-sign]
        (*jvmti_env)->Deallocate(jvmti_env, name_ptr);
                                            ^~~~~~~~
 
Type casting is used to fix the above error. At some places, data type
is changed during field declaration in order to fix the above error.
                                          
Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>