Assembly fixes for Open XL compliance
Few errors were seen while compiling some .s files with
Open XL on z/OS. These were also present with XLC, however
the return code 4 was simply ignored. Open XL reports it as
an error, these changes address these problems.

Additionally, FILE_END definition in zhelpers.m4 was mapped to
add "END\n", effectively adding an extra empty line at the end of
assembly files. This empty line caused a compilation error:
"ASMA140W END record missing"
This addresses the problem by tweaking the definition to map without
the extra line.

Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@ibm.com>