dmpsup.c::appendSystemInfoFromFile only defined on LINUX
While compiling OpenJ9 with Clang 9.1.0 on OSX, the following error is
encountered:

dmpsup.c:1340:1: error: unused function 'appendSystemInfoFromFile'
[-Werror,-Wunused-function]
appendSystemInfoFromFile(J9JavaVM *vm, U_32 key, const char *fileName )
^

ifdefs are consistently used for appendSystemInfoFromFile in order to
fix the above error.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>