Fix JDK8 Windows compilation warning
Fix warning C4800: 'U_32' : forcing value to bool 'true' or 'false'
(performance warning) which caused error C2220: warning treated as error
- no 'object' file generated.

Signed-off-by: Jason Feng <fengj@ca.ibm.com>