Fix max size reporting issue for Large Object Area
	- Update calculating max size for MemoryPool LOA, alignment
	the size with heapAlignment to ceiling instead of floor to match
	PR omr#4451
	- The issue could potentially cause the Exception (in thread
	 "MemoryMXBean notification dispatcher"
	 java.lang.IllegalArgumentException: committed value cannot
	 be larger than the max value)

Signed-off-by: Lin Hu <linhu@ca.ibm.com>