Exclude com.oracle.net.Sdp from ClassloadingTester
Added package com.oracle.net into excludedPackages because
Class.forName("com.oracle.net.Sdp") throws
java.lang.NoSuchMethodException: java.net.SdpSocketImpl.<init>(boolean);

Signed-off-by: Jason Feng <fengj@ca.ibm.com>