Fix compile error
Caused by https://github.com/eclipse/openj9/pull/4168

20:51:30 mmparseXXgc.cpp(950) : error C2220: warning treated as error -
no 'object' file generated
20:51:30 mmparseXXgc.cpp(950) : warning C4244: '=' : conversion from
'double' to 'float', possible loss of data
20:51:30 mmparseXXgc.cpp(964) : warning C4244: '=' : conversion from
'double' to 'float', possible loss of data

Signed-off-by: Aleksandar Micic <amicic@ca.ibm.com>